config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'boards#index'
  resources :forums do
    resources :comments, only: [:new, :create, :edit, :update, :destroy]
    
  end
  resource :profile
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
    
    belongs_to :forum
    belongs_to :user
    validates :content, presence: true
    has_one_attached :avatar
    def play_created_at
        I18n.l(self.created_at, format: :short)
    end
end

app/models/forum.rb
class Forum < ApplicationRecord
    
    belongs_to :user
    has_many :comments, dependent: :destroy
    has_one_attached :eyecatch
    def display_created_at
        I18n.l(self.created_at, format: :short)
    end
    def author_name
        user.display_name
    end
    
end

app/models/profile.rb
class Profile < ApplicationRecord
    belongs_to :user
    has_one_attached :avatar
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :forums, dependent: :destroy 
  has_one :profile, dependent: :destroy
  has_many :comments, dependent: :destroy 
  def display_name
    profile&.nickname || self.email.split('@').first
  end
  def has_written?(forum)
    forums.exists?(id: forum.id)
  end

  def prepare_profile
    profile || build_profile
  end
  def avatar_image
    if profile&.avatar&.attached?
      profile.avatar
    else
      'profile.png'
    end
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
    def index
    end
    
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    

    def new
        forum = Forum.find(params[:forum_id])
        @comment = forum.comments.build
    end

    def create
        forum = Forum.find(params[:forum_id])
        @comment = forum.comments.build(comment_params)
        
        if @comment.save
            redirect_to forum_path(forum), notice: 'コメントを作成しました'
        else
            flash.now[:error] = '更新できませんでした'
            render :new
        end
    end

    def edit
        forum = Forum.find(params[:forum_id])
        @comment = forum.comments.find(params[:id])
    end
    
    def update
        forum = Forum.find(params[:forum_id])
        @comment = forum.comments.find(params[:id])
        if @comment.update(comment_params)
          redirect_to forum_path(forum), notice: '更新しました'
        else
          flash.now[:error] = '更新できませんでした'
          render :edit
        end
    end
    
    def destroy
        forum = Forum.find(params[:forum_id])
        @comment = forum.comments.find(params[:id])
        @comment.destroy!
        redirect_to forum_path(forum), notice: '削除に成功しました'
    end
    
    

    private
    def comment_params
        params.require(:comment).permit(:content).merge(user_id: current_user.id)
    end

end

app/controllers/forums_controller.rb
class ForumsController < ApplicationController
    before_action :set_forum, only: [:show]
    
    def index
        @forums = Forum.all.order("id DESC")
    end

    def show
        @comments = @forum.comments
    end

    def new
        @forum = current_user.forums.build
    end
    
    def create
        @forum = current_user.forums.build(forum_params)
        if @forum.save
          redirect_to forum_path(@forum), notice: '保存しました'
        else
          flash.now[:error] = '保存できません'
          render :new
        end
    end

    def edit
        @forum = current_user.forums.find(params[:id])
    end
    
    def update
        @forum = current_user.forums.find(params[:id])
        if @forum.update(forum_params)
          redirect_to forum_path(@forum), notice: '更新しました'
        else
          flash.now[:error] = '更新できませんでした'
          render :edit
        end
    end
    
    def destroy
        forum = current_user.forums.find(params[:id])
        forum.destroy!
        redirect_to root_path, notice: '削除に成功しました'
    end

    


    private

    def forum_params
        params.require(:forum).permit(:title, :content, :eyecatch)
    end

    def set_forum
        @forum = Forum.find(params[:id])
    end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
    before_action :authenticate_user!

    
    
    def show
    end

    def edit
        @profile = current_user.prepare_profile
    end
    def update
        @profile = current_user.prepare_profile
        @profile.assign_attributes(profile_params)
        if @profile.save
            redirect_to profile_path, notice: 'プロフィールを更新しました'
        else
            flash.now[:error] = '更新できませんでした'
            render :edit
        end

    end


    private
    def profile_params
        params.require(:profile).permit(
            :nickname,
            :introduction,
            :avatar
        )
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/board/index.html.haml
.top
  .container 
    .top-wapper
      .top-title
        %h1 FARNECT
      .top-subtitle
        %p 日本の食を未来へ<br>農業と人を繋ぐ

.container 
  .main-title
    .main-sp 
      %h1 WHAT?<br><br><br>
      %p 仕事として農家を始めたいが<br>どう初めていいかわからないという人たちと
      <br>人手が足らず悩んでいる農家をつなげる<br>
      %p1 そんなことができないかと思いこのサイトを制作しました
    .title-image 
      = image_tag 'tane.png'
.image-second

.container 
  .description  
    .title-image2
      = image_tag 'hatuga.png'
 
    .desc-content   
      %h1 WHY?<br><br><br>
      %p 日本では世界に誇れる特産物がたくさんあります。<br>特に農作物においては日本でしか育てることのできないものも中には存在します。
      %p 日本の農業は農薬や生産技術の向上により<br>農作業にかける時間が減り、 
.container
  .form-section 
    .form-section-button
      %a{:href => "#"} 使ってみる！
.footer-image


.footer
         
      
      

app/views/boards/index.html.haml
.back-image-color
  .container 
    .main-title
      .main-content
        %h1 WHAT?<br><br>
        %p 仕事として農家を始めたいが<br>どう初めていいかわからないという人たちと
        <br>人手が足らず悩んでいる農家をつなげる<br>
        %p1 そんなことができないかと思いこのサイトを制作しました
      .title-image 
        = image_tag 'tane.png'
.image-second

.back-image-color
  .container 
    .description  
      .title-image2
        = image_tag 'hatuga.png'
    
      .desc-content   
        %h1 WHY?<br><br>
        %p 日本の農業はIT化が進み農業者の負担は減ってきてはいますが、
        若者の都市部への進出や土地の形状などの理由によりIT技術を導入出来ない農業者もおり、
        まだまだ一部でしか負担を軽減できていないのが現状です。
        　そこでそういった問題を人と人を繋ぐことで解決できないかと思いました。
        少しでも農業者や農業者として働きたいと考えている方の助けになれれば幸いです。
.container
  .form-section 
    .form-section-button
      =link_to '今すぐ始める', new_user_registration_path
.footer-image


.footer

app/views/comments/edit.html.haml
.container
  .create-wrapper
    = form_with(model: @comment, url: forum_comment_path(@comment.forum), method: 'put', local: true) do |f|
      
      %div
        = f.label :content, '内容'
      %div
        = f.text_area :content, class: 'text'
      = f.submit '保存', class: 'btn-primary'
      = link_to '消去する', forum_comment_path(@comment.forum, @comment.id), data: { method: 'delete', confirm: '本当に削除してもよろしいですか？' }, class: 'btn-border'

app/views/comments/new.html.haml
.container
  .create-wrapper
    = form_with(model: @comment, url: forum_comments_path(@comment.forum), local: true) do |f|
      
      %div
        = f.label :content, 'コメントを追加する'
      %div
        = f.text_area :content, class: 'text'
      = f.submit '保存', class: 'btn-primary'

app/views/forums/_form.html.haml
.container
  .create-wrapper
    = form_with(model: @forum, local: true) do |f|
      %div
        = f.label :eyecatch, '画像を添付'
      %div
        = f.file_field :eyecatch
      %div
        = f.label :title, 'タイトル'
      %div
        = f.text_field :title, class: 'text'
      %div
        = f.label :content, '内容'
      %div
        = f.text_area :content, class: 'text'
      = f.submit '保存', class: 'btn-primary'

app/views/forums/edit.html.haml
= render 'form', forum: @forum
.create-wrapper
  = link_to '消去する', forum_path(@forum), data: { method: 'delete', confirm: '本当に削除してもよろしいですか？' }, class: 'btn-border'

app/views/forums/index.html.haml
.bbs-title
  %h2 掲示板
.container 
  = link_to '新規投稿', new_forum_path, class: 'btn-border'


.container
  .forum-wrapper
    - @forums.each do |forum|
      .forum
        = link_to forum_path(id: forum.id) do
          .forum-title
            = forum.title
          
        .forum_content
          = forum.content

app/views/forums/new.html.haml
= render 'form', forum: @forum

app/views/forums/show.html.haml
.container
  .bbs-title
    %h2 掲示板
.container 
  - if @forum.eyecatch.attached?
    .forum-detail-image
      = image_tag @forum.eyecatch, class: 'forum-eyecatch'
  .forum-detail-wrapper
    .forum-detail
      .forum-detail-title 
        = @forum.title
      - if user_signed_in? && current_user.has_written?(@forum)
        .comment_forum-edit
          = link_to edit_forum_path(@forum) do
            = image_tag 'pen.svg', class: 'edit-img'
      .forum-detail-content 
        = @forum.content
    .forum-detail-avatar 
      = link_to profile_path(@forum.id) do
        = image_tag @forum.user.avatar_image
        
    .forum-detail-info
      %p= @forum.author_name
      %p= @forum.display_created_at
    .comment-button
      = link_to new_forum_comment_path(@forum) do
        %p コメントを追加

- if @comments.present?
  .forum-comment
    %h2 Comment
  - @comments.each do |comment|
    .comment-content
      = comment.content
      .comment_forum-edit
        = link_to edit_forum_comment_path(@forum, comment.id) do
          = image_tag 'pen.svg', class: 'edit-img'
      .comment-detail 
        .comment-detail-avatar 
          = image_tag comment.user.avatar_image
          
        .comment-detail-info
          %p= comment.play_created_at
        

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Farmers
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
    %meta{:content => "width=device-width, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0", :name => "viewport"}/
    
  %body
    %header#header
      .inner
        .header-title
          = link_to 'FARNECT', root_path
        - if user_signed_in?
          %ul.navi
            %li
              =link_to '投稿一覧', forums_path
            %li
              =link_to 'プロフィール', profile_path(current_user)  
          
          = link_to 'ログアウト', destroy_user_session_path, data: { method: 'delete' }, class: 'header_loginBtn'
        - else
          .navi
            = link_to 'ログイン', new_user_session_path, class: 'header_loginBtn'

    .top
      .container 
        .top-wapper
          .top-title
            %h1 FARNECT
          .top-subtitle
            %p 日本の食を未来へ<br>農業と人を繋ぐ
    - if flash.present?
      .flash
        - flash.each do |key, value|
          %div{:class => key}= value


    
    = yield

app/views/profiles/edit.html.haml
.container
  
  .create-wrapper
    %h2 プロフィールを編集する
    = form_with(model: @profile, url: profile_path, method: 'put', local: true) do |f|
      %div
        = f.label :avatar, 'アバター'
      %div
        = f.file_field :avatar
      %div
        = f.label :nickname, 'ハンドルネーム'
      %div
        = f.text_field :nickname, class: 'text'
      %div
        = f.label :intodiuction, '自己紹介'
      %div
        = f.text_area :introduction
        
      = f.submit '保存', class: 'btn-primary'
        

app/views/profiles/show.html.haml
.container
  .profile
    .profile-title 
      %h2 プロフィール
    .profile_img
      = image_tag current_user.avatar_image, class: 'profile-avatar'
    .forum-detail-wrapper
      .profile-wrapper
        %h3 名前
        .profile_name 
          = current_user.display_name
        %h3 自己紹介
        .profile_desc 
          = current_user.profile&.introduction
        - if user_signed_in?
          .profile-edit
            = link_to edit_profile_path do
              = image_tag 'pen.svg', class: 'edit-img'
        